### ISSUE TITLE
SyntaxError: invalid syntax in 2.79

### ISSUE THREAD

**Issue by GitAlekv** [BenjaminSauder/EdgeFlow#4]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\alekv\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\EdgeFlow-master\__init__.py", line 25, in <module>
    from . import (
  File "C:\Users\alekv\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\EdgeFlow-master\op_set_edge_flow.py", line 83
    tension : IntProperty(name="Tension", default=180, min=-500, max=500)
            ^
SyntaxError: invalid syntax

**Comment by DarthMoulByte** [comment]
@GitAlekv do you have a version for 2.79 ??
