### ISSUE TITLE
Error message when trying to use.

### ISSUE THREAD

**Issue by limkork** [BenjaminSauder/EdgeFlow#6]
Hi, 

For a while the add on was working fine, then all of a sudden I am getting this error message:

> edge_loops: 27
> Traceback (most recent call last):
>   File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow\op_set_edge_flow.py", line 114, in invoke
>     result = super(SetEdgeFlowOP, self).invoke(context)
>   File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow\op_set_edge_flow.py", line 68, in invoke
>     self.edgeloops[obj] = util.get_edgeloops(self.bm[obj], edges)
>   File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow\util.py", line 194, in get_edgeloops
>     edge_loops = compute_edgeloop_data(edge_loops)
>   File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow\util.py", line 308, in compute_edgeloop_data
>     find_control_edgeloop(edgeloops, edge_to_Edgeloop)
>   File "C:\Users\lasse\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow\util.py", line 227, in find_control_edgeloop
>     edge_ring.append(edge.link_loops[0])
> IndexError: BMElemSeq[index]: index 0 out of range
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1

Any ideas?

thanks.

**Comment by BenjaminSauder** [comment]
maybe you hit a specific geometry setup I didn't thought after.. or some silly bug - I don't know.
If you can localize it into a very _simple_ model such that reproduction is easy I might look into it.

**Comment by L3ningrad** [comment]
Hi
I have the same situation as **limkork**
For unknown reasons, EdgeFlow stops working and I get an error message:

```
Traceback (most recent call last):
  File "C:\Users\L3ningrad\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow-04\op_set_edge_flow.py", line 124, in invoke
    return self.execute(context)
  File "C:\Users\L3ningrad\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow-04\op_set_edge_flow.py", line 93, in execute
    return self.invoke(context, None)
  File "C:\Users\L3ningrad\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow-04\op_set_edge_flow.py", line 124, in invoke
    return self.execute(context)
  File "C:\Users\L3ningrad\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow-04\op_set_edge_flow.py", line 93, in execute
    return self.invoke(context, None)

  File "C:\Users\L3ningrad\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow-04\op_set_edge_flow.py", line 119, in invoke
    result = super(SetEdgeFlowOP, self).invoke(context)
  File "C:\Users\L3ningrad\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\EdgeFlow-04\op_set_edge_flow.py", line 41, in invoke
    bpy.ops.object.mode_set(mode='OBJECT')
  File "C:\Program Files\Blender Foundation\Blender\2.80\scripts\modules\bpy\ops.py", line 44, in __getattr__
    if module.startswith('__'):
RecursionError: maximum recursion depth exceeded while calling a Python object
location: <unknown location>:-1
```

Before upgrading to version 0.4, everything worked fine
![image](https://user-images.githubusercontent.com/54872588/64218483-80bb8780-ceca-11e9-9106-ede5d852632d.png)

**Comment by BenjaminSauder** [comment]
okay this looks strange indeed... need to check this.

**Comment by limkork** [comment]
My issue went away after a reinstall of Blender.




ons. 4. sep. 2019 kl. 15:02 skrev BenjaminSauder <notifications@github.com>:

**Comment by BenjaminSauder** [comment]
nah i kinda see what is happening in the code - but have a bit of  hard time reproducing it.. ill push an update which .. *hopefully* fixes the infinite recursion call.

please try:
https://github.com/BenjaminSauder/EdgeFlow/releases/tag/0.5

**Comment by L3ningrad** [comment]
The same situation, nothing has changed. Tested on 2.81.5 and 2.80.75
Strange, but why is 0.5 version - 0.2?
![Screenshot_8](https://user-images.githubusercontent.com/54872588/64290032-00e6f900-cf6e-11e9-889b-c1acb935aec0.jpg)
![Screenshot_1](https://user-images.githubusercontent.com/54872588/64290038-02b0bc80-cf6e-11e9-995d-fbb21d2cdb45.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/54872588/64290040-047a8000-cf6e-11e9-8973-c56731a37310.jpg)

**Comment by BenjaminSauder** [comment]
I think you somehow didn't update the addon correctly.

**Comment by L3ningrad** [comment]
![ezgif-1-5bf8a4cb1fc7](https://user-images.githubusercontent.com/54872588/64294602-ea459f80-cf77-11e9-89b8-5a563e820a20.gif)

**Comment by felipefrango** [comment]
I have the same issue, can't install the add-on. The 0.5 link provided also shows up as 0.2 here.

**Comment by old702** [comment]
Had the same error when selecting faces, installed version 0.5 into startup folder - it helped

**Comment by BenjaminSauder** [comment]
Sorry I think I have messed up the release. Could you please try again?

**Comment by felipefrango** [comment]
0.5 working now on Blender 2.81a. 🎈

**Comment by xan2622** [comment]
Hi. 
I just got a similar error with EdgeFlow 0.2 and Blender 2.82 Official, after clicking on **Set Flow**:

```
Traceback (most recent call last):
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\op_set_edge_linear.py", line 28, in invoke
    result = super(SetEdgeLinearOP, self).invoke(context)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\op_set_edge_flow.py", line 68, in invoke
    self.edgeloops[obj] = util.get_edgeloops(self.bm[obj], edges)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\util.py", line 194, in get_edgeloops
    edge_loops = compute_edgeloop_data(edge_loops)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\util.py", line 308, in compute_edgeloop_data
    find_control_edgeloop(edgeloops, edge_to_Edgeloop)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\util.py", line 227, in find_control_edgeloop
    edge_ring.append(edge.link_loops[0])
IndexError: BMElemSeq[index]: index 0 out of range

location: <unknown location>:-1
```


Then I downloaded EdgeFlow 0.5 and I retried (still with Blender 2.82 official), but I still got an error:

```
Traceback (most recent call last):
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\op_set_edge_flow.py", line 116, in invoke
    super(SetEdgeFlowOP, self).invoke(context)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\op_set_edge_flow.py", line 67, in invoke
    self.edgeloops[obj] = util.get_edgeloops(self.bm[obj], edges)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\util.py", line 194, in get_edgeloops
    edge_loops = compute_edgeloop_data(edge_loops)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\util.py", line 308, in compute_edgeloop_data
    find_control_edgeloop(edgeloops, edge_to_Edgeloop)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\util.py", line 227, in find_control_edgeloop
    edge_ring.append(edge.link_loops[0])
IndexError: BMElemSeq[index]: index 0 out of range

location: <unknown location>:-1
```

---

If I click on **Set Linear**, here is the error that I get:

```
Traceback (most recent call last):
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\op_set_edge_linear.py", line 28, in invoke
    super(SetEdgeLinearOP, self).invoke(context)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\op_set_edge_flow.py", line 67, in invoke
    self.edgeloops[obj] = util.get_edgeloops(self.bm[obj], edges)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\util.py", line 194, in get_edgeloops
    edge_loops = compute_edgeloop_data(edge_loops)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\util.py", line 308, in compute_edgeloop_data
    find_control_edgeloop(edgeloops, edge_to_Edgeloop)
  File "C:\Users\Sebastien\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\EdgeFlow\util.py", line 227, in find_control_edgeloop
    edge_ring.append(edge.link_loops[0])
IndexError: BMElemSeq[index]: index 0 out of range

location: <unknown location>:-1
```

**Comment by BenjaminSauder** [comment]
Will close this for now, would need a precise repo instruction to look at it.
